remove deploy_multiple_docs, updated docs.yml to handle the stable and latest aliases.

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -63,25 +63,37 @@ jobs:
           command: |
             pixi run -e docs docs-build-html
 
-            export CURRENT_VERSION=$(grep "__version__" hydromt_wflow/version.py | cut -d= -f 2 | tr -d "\" ")
+      - name: Extract version
+        run: |
+          export CURRENT_VERSION=$(grep "__version__" hydromt_wflow/version.py | cut -d= -f 2 | tr -d "\" ")
 
-            if [ -z "$CURRENT_VERSION" ]; then
-              echo "Could not determine version, exiting..."
-              exit 1
-            fi
+          if [ -z "$CURRENT_VERSION" ]; then
+            echo "Could not determine version, exiting..."
+            exit 1
+          fi
 
-            if echo "$CURRENT_VERSION" | grep -q "dev"; then
-              echo "DOC_VERSION=dev" >> "$GITHUB_ENV"
-            else
-              echo "DOC_VERSION=v$CURRENT_VERSION" >> "$GITHUB_ENV"
-            fi
+          if echo "$CURRENT_VERSION" | grep -q "dev"; then
+            echo "DOC_VERSION=dev" >> "$GITHUB_ENV"
+          else
+            echo "DOC_VERSION=v$CURRENT_VERSION" >> "$GITHUB_ENV"
+          fi
 
       - name: Prepare versioned docs directory
         if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref_name, 'feat/private-docs') }}
         run: |
-          rm -rf site/${DOC_VERSION}
-          mkdir -p site/${DOC_VERSION}
-          cp -r docs/_build/html/* site/${DOC_VERSION}/
+          if [ "${DOC_VERSION}" = "dev" ]; then
+            # dev version: update /latest alias
+            rm -rf site/${DOC_VERSION} site/latest
+            mkdir -p site/${DOC_VERSION} site/latest
+            cp -r docs/_build/html/* site/${DOC_VERSION}/
+            cp -r site/${DOC_VERSION} site/latest
+          else
+            # release version: update /stable alias
+            rm -rf site/${DOC_VERSION} site/stable
+            mkdir -p site/${DOC_VERSION} site/stable
+            cp -r docs/_build/html/* site/${DOC_VERSION}/
+            cp -r site/${DOC_VERSION} site/stable
+          fi
 
       - name: Setup Pages
         if: ${{ github.event_name != 'pull_request' }}
