Updated caching of workflows; inline with core; clock on dev test

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -43,25 +43,39 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v3
 
-      - name: Setup Mambaforge
-        uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-          miniforge-variant: Mambaforge
-          miniforge-version: latest
-          activate-environment: hydromt_wflow
-          use-mamba: true
-
-      - name: Generate env spec
+      - name: Generate env yaml
         run: |
           pip install tomli
-          python make_env.py doc --py-version ${{ matrix.python-version }}.*
+          python make_env.py doc -p ${{ matrix.python-version }}.* -n hydromt_wflow
 
+      - name: Load cache
+        id: cache
+        uses: actions/cache/restore@v3
+        with:
+          path: |
+            /usr/share/miniconda3
+            ~/pycache
+            ./docs/_build
+          # the below two settings mean we'll alway srestore the cache
+          # but the cache hit output can tell us if we have to update afterwards
+          key: docs-${{ hashFiles('environment.yml')  }}
+          restore-keys: |
+            docs
+
+      - name: Failed cache restore
+        if: steps.cache.outputs.cache-matched-key == ''
+        run: |
+          echo "Failed to restore any cache. exiting..."
+          exit 1
+
+      # by avoiding the mamba setup stage by loading it from cache instead we save
+      # a lot of setup time, but we do have to do our own PATH management
+      # hence the exports
       - name: Update environment
-        run: mamba env update -f environment.yml
-
-      - name: Install HydroMT-Wflow plugin
-        run: pip install .
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          mamba env update -n hydromt_wflow -f environment.yml
 
       - name: Generate dummy docs
         if: ${{ github.event_name == 'pull_request' }}
